services:
  students-delete-service:
    build: .
    container_name: students-delete-service
    ports:
      - "8085:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - mongo-network
networks:
  mongo-network:
    external: true
    name: mongo-network

